# Generated by Django 2.0.2 on 2018-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('CH', 'Switzerland'), ('FR', 'France'), ('BE', 'Belgium')], max_length=2)),
                ('city', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('room_quantity', models.PositiveSmallIntegerField()),
                ('person_quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='house_images')),
            ],
        ),
    ]
