# Generated by Django 2.0.2 on 2018-03-16 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180316_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
